name: 'Author Dynamic Checklist'
description: 'Adds dynamic checkings to PR description'
inputs:
  GITHUB_TOKEN:
    description: Auth token for Testing Github action
    required: true
runs:
  using: 'node16'
  main: './index.js'
