name: PR Author dynamic Checklist

on:
  pull_request:

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: github.actor != 'OSBotify'
    steps:
      - name: dynamicChecksInPrDescription.js
        uses: sebryu/github-actions-generated-comments/.github/actions/javascript/dynamicChecksInPrDescription@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
